### PR TITLE
Revamped weapons/ammo | Bug fixes and general improvements

### PR DESCRIPTION
**Pull request by thelindat**
## Weapon and ammo
* Updated ammos to use calibres `(.45, 9mm, 5.56, etc.)`
* Firearms now load with the appropriate calibre instead of `rifle-ammo, pistol-ammo, etc.`
* Guns will now only load a single clip.
* Ammo is individual items - loading `WEAPON_PISTOL` will remove 12 `ammo-9`, or whatever amount is missing.
* Shooting your last bullet will attempt to reload your weapon.
* Ammo items are now set at realistic weights.
* More information is stored as `currentWeapon`
* Full components support and adding components with items

## Items
* If items exist in the config but not the database they will be created with dummy data (you should still add them to the database)
* Use `item` instead of `data.item` when triggering itemUse events
* Add `metadata.type` - example used by `['keys'] = metadata = { type = 'lspd' }`
* Identification now sets `xPlayer.getName()` as `metadata.type`, other information is in `metadata.description`
* All items will receive metadata (even if it's a blank table)
* Check metadata when merging items, only allow them to combine if they match

## Inventory
* Resolved an issue when opening inventory too soon after dropping an item failed to open the drop
* Do not allow items to be dropped if ped/coords cannot be found by the server (OneSync)
* Add a server warning to enable OneSync when somebody tries to create a drop
* Set maxweight in the config instead of ESX
* Fixed weight displays on item slots
* Adjust weapon weight based on ammo count (still WIP)
* Display individual item weight on tooltip
* Cleaner item tooltips
* More appearance changes (font size, font family, image position, etc.)
* Entering amounts such as `00001` will act as if you entered `0` when moving items
* Properly saves when moving items around in the shop
* Prevent item swapping between inventories
* `/evidence #` command for police to use while near evidence room (Config.PoliceEvidence)

## Other
* Support for non-OneSync (should really use it though)
* Support for old inventory data (conversion)

```
Accounts table = {"bank":1701,"money":845,"black_money":0}
Inventory table = {"WEAPON_PISTOL":1, "water":1, "burger":1}
```
Will convert to
```
[{"metadata":{"components":[],"ammoweight":0,"durability":100,"ammo":0,"weaponlicense":"486811HSN231955"},"slot":1,"name":"WEAPON_PISTOL","count":1},{"metadata":[],"slot":2,"name":"water","count":1},{"metadata":[],"slot":3,"name":"burger","count":1},{"metadata":[],"slot":4,"name":"money","count":845}]
```
 

## Fixed a major bug with weight values and item transfers
Everything was getting processed then sent to the server to do some validations, but if you failed an item transfer from a stash to your inventory, it would show the item in your inventory and allow you to move it back (until closing inventory) - duplicating the item if you moved it to a new slot.
https://streamable.com/y2a4rr

### CODE REVIEW

**Comment by Ruqen** [comment]
Looking forward to this being done.

**Comment by thelindat** [comment]
I was originally going to release at 1.4.0, but new bugs were being made and fixed as I changed things.
I just released 1.4.3 and am pending bug reports - if there's nothing game breaking (like duping) then it will be ready to pull.

**Comment by Ruqen** [comment]
Thanks for your support on hsn-inventory, but I'd like you to resolve the conflicts ^^

**Comment by thelindat** [comment]
> 
> 
> Thanks for your support on hsn-inventory, but I'd like you to resolve the conflicts ^^

Conflicts are from merging bazookan's get charname PR - it's checking the database for the player firstname and lastname instead of xPlayer.getName() so I didn't pull it to mine

**Comment by thelindat** [comment]
She's good to go

**Comment by Ruqen** [comment]
Is this ready to go or still in need of bug testing?

**Review by Ruqen — APPROVED** [review]

**Comment by Ruqen** [comment]
Merged #10 into main.

**Pull request merged**
